### ISSUE TITLE
Keeping track of the new ordering

### ISSUE THREAD

**Issue by SylvieC** [wintvelt/elm-sortable-list#3]
Hi, thank you for the example and the package!I
When I have the items reordered, I need to send to the server the new order. 
I don't know how to do that.
Is there a way to keep track of the new order (assuming each row also had an id to start), to send the new indexing to the server? 
The idea is to get something like this where order represents the new order

```
{"items"=>{"0"=>{"item_id"=>"114", "order"=>"0"}, "1"=>{"item_id"=>"23", "order"=>"1"}, "2"=>{"item_id"=>"24", "order"=>"2"}, "3"=>{"item_id"=>"22", "order"=>"3"}, "4"=>{"item_id"=>"25", "order"=>"4"}, "5"=>{"item_id"=>"78", "order"=>"5"}}, "action"=>"update_all", "controller"=>"branches"}
```

**Comment by wintvelt** [comment]
Unfortunately it has been a while since I worked in Elm, but below are some tips.
Hope these are helpful!

**1. Extend the model/ code to sort a list if records, instead of a list of simple strings**
- It looks like the data you need per item is a bit more than just a `String`. So in the example code, you could replace the [line 30](https://github.com/wintvelt/elm-sortable-list/blob/master/src/elm-sortable-list.elm#L30) with something like `, data : List MyItem`, and define a type alias with your item, like `type alias MyItem = { id : Int, title : String }`
- then you would need to change your initialList also to hold a list of records instead of a list of strings
- change [line 38](https://github.com/wintvelt/elm-sortable-list/blob/master/src/elm-sortable-list.elm#L38) from `List.sort` to `List.sortBy` to tell Elm to sort by the id (probably), or remove the sort altogether
- in the `itemView` function on [line 227](https://github.com/wintvelt/elm-sortable-list/blob/master/src/elm-sortable-list.elm#L227) you need to modify the code to show the title of the item, because item is now a record, and not a simple string.

**2. Send the sorted list (of records) to a server**
This would require adding functions for

a) invoke the 'send to server' functions at a logical place in the code
Probably the most logical place is at the `DragEnd` event, where you add a Cmd when the list is updated. This is in [line 113](https://github.com/wintvelt/elm-sortable-list/blob/master/src/elm-sortable-list.elm#L113)

b) create a message (looks like json-ish structure in your comment)
The source for your message is list of records in `model.data`. But take care here: you need the updated version of the model, not the original model.data. So probably create a `let newModel = ... in ` structure.
This list in the (updated) model is already sorted in the new order, and has the right id's, so you could use functions in JSON package of elm to convert your list of records to the desired JSON output.

c) send the message to the server
Several ways to do this. Most basic is an `HTTP.send` command. You could look this up in the docs, or learn by example (e.g. [here](https://elmprogramming.com/http-requests-post.html#submitting-a-new-post-to-server))

**Comment by SylvieC** [comment]
Thanks you so much for your detailed answer. I really appreciate it!
